version: '3.3'

services:
  article:
    build: 
      context: .
      dockerfile: article/dockerfile
    image: article:1.0
    container_name: article-service
    environment:
      MONGO_HOST: mongo:27017
    ports:
      - 8001:8001
    depends_on:
      - mongo
    volumes:
      - blog:/article
    networks:
      - blog

  user:
    build: 
      context: .
      dockerfile: user/dockerfile
    image: user:1.0
    container_name: user-service
    ports:
      - 8002:8002
    volumes:
      - blog:/user
    networks:
      - blog

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    image: front:1.0
    container_name: front-service
    environment:
      ARTICLE_HOST: article:8002
      USER_HOST: user:8001
    depends_on:
      - article
      - user
    ports:
      - 8003:8003
    volumes:
      - blog:/front
    networks:
      - blog

  mongo:
    image: mongo:5.0.9
    container_name: mongo
    networks:
      - blog

volumes:
  blog: 

networks:
  blog:
    driver: bridge
